"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
right_format = "($nodejs) ($bun)"

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[â¯](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = "[â¯](bold red)"

[container]
disabled = true

[line_break]
disabled = false

[directory]
fish_style_pwd_dir_length = 0
truncation_length = 1
truncation_symbol = "ğŸ  "
read_only = "ğŸ”’ "
style = "yellow bold"
disabled = false


[package]
disabled = true

[azure]
disabled = false
format = '[$symbol($subscription)($duration)]($style) '
symbol = "â˜ï¸  "
style = 'blue bold'

[git_branch]
symbol = 'ğŸŒ± '
truncation_symbol = ''
format = "[$symbol$branch(:$remote_branch)]($style) "
ignore_branches = ['master', 'main']
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'
disabled = false

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style):[-$deleted]($deleted_style) '
disabled = false

[sudo]
disabled = true

[git_status]
conflicted = 'ğŸ˜¶â€ğŸŒ«ï¸'
ahead = 'ğŸ’¨'
behind = 'ğŸ’¤'
diverged = 'ğŸ¤ª'
up_to_date = 'ğŸ‘'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = 'ğŸ‘€'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘ï¸ '
disabled = false


[nodejs]
format = '[ğŸš€ $version](bold green) '
disabled = false

[os]
disabled = false

[rust]
format = '[$symbol$version]($style) '
symbol = 'ğŸ¦€ '
style = 'bold red'
disabled = false
